spring:
  application:
    name: caseStudy

  # database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/case_study
    username: postgres
    password: admin

  # Jpa configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # sql configuration
  sql:
    init:
      mode: always

# swagger-ui configuration
springdoc:
  swagger-ui:
    path: /show-swagger

server:
  port: 8080